#x=10
#y=2
#resultat=x/y
#print(f"{x} devided by {y} equals {resultat}") 

#hourly_wage =20.0
#hours=6
#day="Sunday"
#daily_wages =hourly_wage* hours
#if day =='sunday':
#   daily_wages*2


# import logging 
#logging.basicConfig(level=logging.DEBUG)
#def add(a,b):
  #return a+b

#def test_add():
  #assert add(2,3)==5
  #assert add(-1,1)==0

word=input("Please type in a word :")
if len(word)>1:
  print(f"there are {len(word)} in the word {word} Thank you!")
else:
  print("Thank you!")